language: node_js
node_js:
- '5'

before_install:
- export DISPLAY=:99.0

addons:
  firefox: '45.0'

before_script:
- sh -e /etc/init.d/xvfb start
- sleep 1

deploy:
- provider: cloudfoundry
  username:
    secure: r0pKjmMZAnyTKllxP/DO5erVIQtnHVh/jm84+gsi263gzfrELYftya29BXiIRxwiInE7q8kx54N3ZUwi/X7tO9M3TWlyWrO6X6ZJKHHbHl1Pm1Yv7yIY0Qm1tPV2TITaQ5XiT9B3IHtvCWhJBOuxaAzjXKjftPLjYlG/sMXT6P8ly4kMfmr44B8hDPLHMJlV9N2zExj4nOe587jLciI2lDOQksvVi7KP29OvZYXEBCgwY1XOCevDHmqpwHPOH9JUozLXJhucX5BGn2zQrAX9D3BpIftHZyao3UNQQaTh/q0gvATz5AY+jQb3fHJtXOxOElb7JdrpD7wbfS7dFnV0Pu+hAmkLFKtPiS52KODrvDesKaqnbn69d+cI5qUdLe4eNNjF5YVHRQ2SZ1tcUDsmfRZBbk8so3fUnv7Mr+5e2kfR1HdTg9UAZOaMXBc6G5fatUmLGNCtJKkp+rWSEZ58uZUywO1zl2X7TDOmGsF3JmhScR5DndY4iGg+3iJqBHm6AgRCbwXHlycb9fUg+YnrF7lQkMyBLyd/YPOaYYZLfr8K/KGRoztwTEbHCA7GKHSB8bQV0+ZwZEUoZMIJZq6vc8HOXQD2JddvgE1Oppru2HZtCH+KVkv5ZFxJ1LAWV0dg6hl6moslSp4QP53qlRWuNFWEff8AJGpe1bDxWhycXDU=
  password:
    secure: U0Weyo26F5pNpa/cg0pbHywiGo8MvnxYlstig9s4vblDnWNv1Hqjq2t98GQEX9zjwDE1eOyBFMD142FuWid1d5bUn1R1y6psdtJhbNq6ZkTH6y8Bsgj8u8+OWBaxBCbrHJr88PbLdNEhs6boL7x56q/Nh6U+7dDU+xDP5fwNZx4RUQ9o+M3kH3B4GiwCNM288UNTd5THZ4rL+H3qLqQ8poq5+8RkAw6Ts0KY7txvjkfwNWX7glLZh0oIb95PyVld+Zh7TPTOnD40kxt6uXMK+8ydTPOcd3BIuSs7aeDALfYgHyBe6sOcnYfJH49IcOZ4HMJJRIzwTkHMNyme/ng/E0ol2D9Sw3eOQGZXCHrMfaOClCOwV/dSb2Yyh5KzK+Gq07fF3D3pO+6YlSfkomMpwtsICdfQOfEWNZGHueyMj+3QsR7OKCZV7vv67wDo6Man3Wl5G2mx3rh3BVGZXzGlg6DfQf6TJzpDUoQKPTTBoHxEoNUUuo6tMtShfwn+kZNdpEqVTfpUbJ6PDOmyo1bkSBL8y2XoG/GrFiJJT249q5Bs4s9LwPq+Yq0Ap/LbPIWxGksQSh8rSoc7eWCT7sDVf1dKVdwd4EBUFWlkSoxPWBht6E3YAimPpwL7+hdPkoblY8Kme51/hAh4hpmSFu5zqK3mKnU6uZkpsjoRc2GxwJU=
  api: https://api.run.pivotal.io
  organization: Catulla
  space: development
